Repository Lambda-School-Labs/sfmta-data-analysis-ds, pull requests merged in 2020-06, with the labels that each got.

#26 Schedule class
  sfmta-api/schedule.py
Labels: enhancement

#27 Wrote and deployed a function to collect raw route data into the DB
  AWS_Lambda/README.md
  AWS_Lambda/route_collector.py
  AWS_Lambda/route_function.zip
Labels: enhancement

#29 Api/schedule/housekeeping
  .gitignore
  exploratory_notebooks/On-Time_FirstLook.ipynb
  requirements.txt
  sfmta-api/__init__.py
  sfmta-api/app.py
  sfmta-api/requirements.txt
  sfmta-api/schedule.py
Labels: bugfix, dependencies, enhancement, refactoring

#31 Bunches & Gaps
  exploratory_notebooks/B&G_FirstLook.ipynb
Labels: enhancement

#33 pushing exploratory notebooks to document process
  exploratory_notebooks/bunches_and_gaps/B&G_FirstLook.ipynb
  exploratory_notebooks/bunches_and_gaps/B_And_G_With_GeoJson.ipynb
  exploratory_notebooks/bunches_and_gaps/B_And_G_With_GeoJson_v2.ipynb
Labels: enhancement

#34 updated api docs
  sfmta-api/README.md
  sfmta-api/TODO.md
Labels: documentation

#36 Updated main and api readmes;
  README.md
  sfmta-api/README.md
Labels: documentation

#39 fixed another broken link
  README.md
Labels: documentation

#40 Updated report generation readme with the location loading optimization
  AWS_Lambda/Report_Generation/readme.md
Labels: documentation

#42 Architecture diagram and description
  README.md
  images/architecture_diagram.png
Labels: documentation

#43 Documentation
  DATAREADME.md
Labels: documentation

#45 updates to main and data readmes
  DATAREADME.md
  README.md
Labels: documentation

#46 Adding Labs 22 database info to the deprecated assets readme
  deprecated_assets/datasets/README.md
Labels: documentation
