Repository Lambda-School-Labs/sfmta-data-analysis-ds, pull requests merged in 2020-05, with the labels that each got.

#13 Fixed timezone handling from UTC to PST during daily querying;
  jordan-sfmta-api/__pycache__/app.cpython-37.pyc
  sfmta-api/Dockerfile
  sfmta-api/app.py
Labels: bugfix

#19 New version of CalculatingStops; made dramatic changes to function to…
  exploratory_notebooks/CalculatingStops_Improved.ipynb
Labels: bugfix, refactoring

#20 Committing updated stop assignment notebook
  exploratory_notebooks/calculating_stops/CalculatingStops_FirstLook.ipynb
  exploratory_notebooks/calculating_stops/CalculatingStops_Improved.ipynb
  exploratory_notebooks/calculating_stops/CalculatingStops_Improved_v2.ipynb
Labels: bugfix, enhancement

#17 Collecting schedules into our database
  AWS_Lambda/schedule_collector.py
  AWS_Lambda/schedule_function.zip
Labels: enhancement

#22 Mapping
  exploratory_notebooks/calculating_stops/CalculatingOnTime%_FirstLook.ipynb
  exploratory_notebooks/mapping/Mapping_FirstLook.ipynb
  exploratory_notebooks/mapping/nbus_single.html
Labels: enhancement

#24 fixing dangling imports
  sfmta-api/app.py
Labels: bugfix
